Reconfiguration of noisefloor-, threshold-, power-references.
PerCollECT/LidarLimbs pull request #35
Opened 2023-08-07 14:29 UTC by TimoHinsemann

fixes #34

2023-08-08 11:32 UTC, ClemensLinnhoff requested changes
Looks good, but I would remove the connection between "Low received power" (54) and "false negative detection" (0), because it is still connected via "Received power below threshold" (39)

2023-08-22 06:42 UTC, ClemensLinnhoff commented
Does it make sense to introduce a node "Received power above detection threshold"? Then False positive detection would be analog to false negative detection? Maybe we can discuss this in our next meeting @TimoHinsemann.

2023-09-27 13:40 UTC, TimoHinsemann commented
> Does it make sense to introduce a node "Received power above detection threshold"? Then False positive detection would be analog to false negative detection? Maybe we can discuss this in our next meeting @TimoHinsemann.

@ClemensLinnhoff until the next meeting, could you maybe check and - if everything's fine - accept this merge first? (I am not sure if the two commits that I did after my request are included, if you merge now. I hope so). Because I would suggest to open another issue for your comment, after we talk in the next meeting. Also there is another "new" branch to be done after my talk to Philipp and I would prefer to take the "master" as a template for that. - (Else I would need to implement possible changes into more than one branch, which is confusing regarding the up-going numbers of new nodes in each branch). Is that possible?

2023-09-28 08:06 UTC, ClemensLinnhoff approved these changes

2023-09-28 08:06 UTC, merged