Adding parentIds for motion scan effect
PerCollECT/LidarLimbs pull request #46
Opened 2024-06-18 10:37 UTC by PhRosenberger

As written in #45, the motion scan effect node is currently flying around besides the tree.
This PR should solve it.

2024-06-18 11:39 UTC, ClemensLinnhoff requested changes
See my comment in the corresponding issue. I do not see the motion scan effect producing false positives or false negatives. The detections are all valid, just at a different position than expected.

2024-06-18 20:13 UTC, PhRosenberger commented
> See my comment in the corresponding issue. I do not see the motion scan effect producing false positives or false negatives. The detections are all valid, just at a different position than expected.

I just inserted the detection state error node for this.

2024-06-18 20:16 UTC, PhRosenberger commented
@TimoHinsemann as this PR inserts several parentIDs, I guess I also need to provide references for each of these new connections, right?

2024-06-25 08:53 UTC, PhRosenberger commented
This PR relates to #37 based on #36. We should somehow merge/discuss both concepts.

2025-01-30 07:03 UTC, ClemensLinnhoff commented
What about this PR @TimoHinsemann? Is it out-dated and can be closed?

2025-01-30 11:06 UTC, TimoHinsemann commented
> What about this PR @TimoHinsemann? Is it out-dated and can be closed?

Hey @ClemensLinnhoff, yes, with the last update of the develop-branch, the issues #36, #42, #45 and #48 should be solved. So this PR here can be closed. A double-check from your side - to be on the safe side - would be maybe useful. After that, we should merge the develop-branch into the main-branch. I will create a PR for that now. 

@PhRosenberger I am very sorry for not reaching out after your last comment here, not only the thesis was stealing my time but also I missed to change my Notification-Mail-Adress to the company adress. I hope the new commits are in your interest!

2025-01-30 12:18 UTC, closed without merging